variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: ubuntu:focal
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq > /dev/null
    - apt-get install -yq -qq build-essential git cmake qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools sudo apt-get install libxcb-xinerama0-dev build-essential perl python git "^libxcb.*" libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev flex bison gperf libicu-dev libxslt-dev ruby libssl-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libfontconfig1-dev libcap-dev libxtst-dev libpulse-dev libudev-dev libpci-dev libnss3-dev libasound2-dev libxss-dev libegl1-mesa-dev gperf bison libbz2-dev libgcrypt20-dev libdrm-dev libcups2-dev libatkmm-1.6-dev libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libbluetooth-dev bluetooth blueman bluez libusb-dev libdbus-1-dev bluez-hcidump bluez-tools libbluetooth-dev libgles2-mesa-dev qtconnectivity5-dev libqt5gamepad5-dev qtpositioning5-dev > /dev/null
  script:
    - ./build_lin
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/lin/vesc_tool_original_linux.zip

